# Generated by Django 3.2.12 on 2022-03-09 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_useremails'),
    ]

    operations = [
        migrations.AddField(
            model_name='useremails',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
